### ISSUE TITLE
Add ephemeral container-based helper for pod-level disruption

### ISSUE THREAD

**Issue by pablochacin** [grafana/k6-chaos#7]
[Ephemeral containers](https://kubernetes.io/docs/concepts/workloads/pods/ephemeral-containers/) are containers that can be added to running pods. They are intended to be used for debugging purposes (for example, the [kubectl debug](https://kubernetes.io/docs/tasks/debug-application-cluster/debug-running-pod/#ephemeral-container) command adds an ephemeral container).

Using ephemeral containers for chaos engineering will allow injecting chaos behavior to specific pods without affecting other pods deployed in the same cluster. 

This idea is explored in the [pod-chaos](https://github.com/pablochacin/pod-chaos) project using shell scripts. This approach can be easily ported to `k6-chaos` as a helper function.

**Comment by ppcano** [comment]
@pablochacin, great idea! We want this project to support these cases.  

It is specified on the project readme: [`exhaustCPU` and `exhaustMemory `](https://github.com/grafana/k6-chaos#wip), do you have any proposals for the k6 API? 

It would be good to show a k6 script to get an overview of what the APIs could look like.

**Comment by pablochacin** [comment]
> do you have any proposals for the k6 API?

Not yet, but the idea is initially have these methods:
-  install:  creates the ephemeral container 
- delay: introduces delays with a mean delay and some random variation. Reproduces  slow networks,
- drop: drop a percentage of traffic. Reproduces flaky networks.
- kill: kill a container in a pod (but not the pod). This is interesting for testing health probes, load balancer, etc.

I was also considering this:
- exhaust: consume CPU and memory resources for the pod. I'm not sure if this use case is relevant as the resources consumption can be forced by increasing the traffic. 


It is important to keep in mind that these tests affect only one pod. Other pods in the cluster are not affected by the tests, so there is total isolation. Therefore pod level tests and node level tests complement each other.

**Comment by pablochacin** [comment]
Closed by https://github.com/grafana/k6-chaos/pull/15
